### ISSUE TITLE
Function Request?

### ISSUE THREAD

**Issue by srobadelic** [Codydanieljones/Service-Now-Alerts#2]
Couldn't find a place to suggest code changes, so this is not an issue but thought I would mention. I have no idea how to code, but I did install this and it's fricking amazing. I was looking at some options to control the amount of time a notification appears on Chrome. I am seeing requireInteraction as one option on the Chrome Dev site, but Google search and Applescript are the limits to my coding skills. But what a great extension!

**Comment by Codydanieljones** [comment]
Thanks. I will look into this and see about making it an option.
