### ISSUE TITLE
notification

### ISSUE THREAD

**Issue by wobeng** [Codydanieljones/Service-Now-Alerts#3]
Hi,

How often is notify url checked? 

Do we get a browser notification or batch number only

**Comment by Codydanieljones** [comment]
It should be checked every minute for a new count of tickets in the queue. The notification will show just the most recent INC number.

**Comment by wobeng** [comment]
@Codydanieljones Thanks for your fast response :)

I have a critical queue I want to monitor in seconds. Is it possible to expose the number of seconds to check queue in options?

Also is it possible for it to push a browser notification?
